//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OldXamarinAdroid.ImotorCareWebApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImotorCareWebApiSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rating_table_support))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Personel_rating_view_support))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Personel_table_support))]
    public partial class ImotorCareWebApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllFromTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchForSpecialityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllFromTypeWithDistanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonelByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePersonelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback RatePersonelOperationCompleted;
        
        private System.Threading.SendOrPostCallback Personel_RatingsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImotorCareWebApi() {
            this.Url = "http://10.150.35.240:8005/ImotorCareWebApi.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;
        
        /// <remarks/>
        public event GetAllFromTypeCompletedEventHandler GetAllFromTypeCompleted;
        
        /// <remarks/>
        public event SearchForSpecialityCompletedEventHandler SearchForSpecialityCompleted;
        
        /// <remarks/>
        public event GetAllFromTypeWithDistanceCompletedEventHandler GetAllFromTypeWithDistanceCompleted;
        
        /// <remarks/>
        public event GetPersonelByIDCompletedEventHandler GetPersonelByIDCompleted;
        
        /// <remarks/>
        public event UpdatePersonelCompletedEventHandler UpdatePersonelCompleted;
        
        /// <remarks/>
        public event GetDataSetCompletedEventHandler GetDataSetCompleted;
        
        /// <remarks/>
        public event RatePersonelCompletedEventHandler RatePersonelCompleted;
        
        /// <remarks/>
        public event Personel_RatingsCompletedEventHandler Personel_RatingsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Personel_table[] GetAll() {
            object[] results = this.Invoke("GetAll", new object[0]);
            return ((Personel_table[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAsync(object userState) {
            if ((this.GetAllOperationCompleted == null)) {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[0], this.GetAllOperationCompleted, userState);
        }
        
        private void OnGetAllOperationCompleted(object arg) {
            if ((this.GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllFromType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Personel_table[] GetAllFromType(string type) {
            object[] results = this.Invoke("GetAllFromType", new object[] {
                        type});
            return ((Personel_table[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllFromTypeAsync(string type) {
            this.GetAllFromTypeAsync(type, null);
        }
        
        /// <remarks/>
        public void GetAllFromTypeAsync(string type, object userState) {
            if ((this.GetAllFromTypeOperationCompleted == null)) {
                this.GetAllFromTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFromTypeOperationCompleted);
            }
            this.InvokeAsync("GetAllFromType", new object[] {
                        type}, this.GetAllFromTypeOperationCompleted, userState);
        }
        
        private void OnGetAllFromTypeOperationCompleted(object arg) {
            if ((this.GetAllFromTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFromTypeCompleted(this, new GetAllFromTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchForSpeciality", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Personel_rating_view[] SearchForSpeciality(string speciality, string longitude, string latitude, double range) {
            object[] results = this.Invoke("SearchForSpeciality", new object[] {
                        speciality,
                        longitude,
                        latitude,
                        range});
            return ((Personel_rating_view[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchForSpecialityAsync(string speciality, string longitude, string latitude, double range) {
            this.SearchForSpecialityAsync(speciality, longitude, latitude, range, null);
        }
        
        /// <remarks/>
        public void SearchForSpecialityAsync(string speciality, string longitude, string latitude, double range, object userState) {
            if ((this.SearchForSpecialityOperationCompleted == null)) {
                this.SearchForSpecialityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchForSpecialityOperationCompleted);
            }
            this.InvokeAsync("SearchForSpeciality", new object[] {
                        speciality,
                        longitude,
                        latitude,
                        range}, this.SearchForSpecialityOperationCompleted, userState);
        }
        
        private void OnSearchForSpecialityOperationCompleted(object arg) {
            if ((this.SearchForSpecialityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchForSpecialityCompleted(this, new SearchForSpecialityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllFromTypeWithDistance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Personel_table[] GetAllFromTypeWithDistance(string longitude, string latitude, string type, int range) {
            object[] results = this.Invoke("GetAllFromTypeWithDistance", new object[] {
                        longitude,
                        latitude,
                        type,
                        range});
            return ((Personel_table[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllFromTypeWithDistanceAsync(string longitude, string latitude, string type, int range) {
            this.GetAllFromTypeWithDistanceAsync(longitude, latitude, type, range, null);
        }
        
        /// <remarks/>
        public void GetAllFromTypeWithDistanceAsync(string longitude, string latitude, string type, int range, object userState) {
            if ((this.GetAllFromTypeWithDistanceOperationCompleted == null)) {
                this.GetAllFromTypeWithDistanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFromTypeWithDistanceOperationCompleted);
            }
            this.InvokeAsync("GetAllFromTypeWithDistance", new object[] {
                        longitude,
                        latitude,
                        type,
                        range}, this.GetAllFromTypeWithDistanceOperationCompleted, userState);
        }
        
        private void OnGetAllFromTypeWithDistanceOperationCompleted(object arg) {
            if ((this.GetAllFromTypeWithDistanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFromTypeWithDistanceCompleted(this, new GetAllFromTypeWithDistanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPersonelByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Personel_table GetPersonelByID(string id) {
            object[] results = this.Invoke("GetPersonelByID", new object[] {
                        id});
            return ((Personel_table)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonelByIDAsync(string id) {
            this.GetPersonelByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void GetPersonelByIDAsync(string id, object userState) {
            if ((this.GetPersonelByIDOperationCompleted == null)) {
                this.GetPersonelByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonelByIDOperationCompleted);
            }
            this.InvokeAsync("GetPersonelByID", new object[] {
                        id}, this.GetPersonelByIDOperationCompleted, userState);
        }
        
        private void OnGetPersonelByIDOperationCompleted(object arg) {
            if ((this.GetPersonelByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonelByIDCompleted(this, new GetPersonelByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePersonel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdatePersonel(string id, string name, string garage, string type, string speciality, string longitude, string latitude) {
            object[] results = this.Invoke("UpdatePersonel", new object[] {
                        id,
                        name,
                        garage,
                        type,
                        speciality,
                        longitude,
                        latitude});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePersonelAsync(string id, string name, string garage, string type, string speciality, string longitude, string latitude) {
            this.UpdatePersonelAsync(id, name, garage, type, speciality, longitude, latitude, null);
        }
        
        /// <remarks/>
        public void UpdatePersonelAsync(string id, string name, string garage, string type, string speciality, string longitude, string latitude, object userState) {
            if ((this.UpdatePersonelOperationCompleted == null)) {
                this.UpdatePersonelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePersonelOperationCompleted);
            }
            this.InvokeAsync("UpdatePersonel", new object[] {
                        id,
                        name,
                        garage,
                        type,
                        speciality,
                        longitude,
                        latitude}, this.UpdatePersonelOperationCompleted, userState);
        }
        
        private void OnUpdatePersonelOperationCompleted(object arg) {
            if ((this.UpdatePersonelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePersonelCompleted(this, new UpdatePersonelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetClass[] GetDataSet() {
            object[] results = this.Invoke("GetDataSet", new object[0]);
            return ((SetClass[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataSetAsync() {
            this.GetDataSetAsync(null);
        }
        
        /// <remarks/>
        public void GetDataSetAsync(object userState) {
            if ((this.GetDataSetOperationCompleted == null)) {
                this.GetDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataSetOperationCompleted);
            }
            this.InvokeAsync("GetDataSet", new object[0], this.GetDataSetOperationCompleted, userState);
        }
        
        private void OnGetDataSetOperationCompleted(object arg) {
            if ((this.GetDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataSetCompleted(this, new GetDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RatePersonel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RatePersonel(string id, string comment, string numberOfStars) {
            object[] results = this.Invoke("RatePersonel", new object[] {
                        id,
                        comment,
                        numberOfStars});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RatePersonelAsync(string id, string comment, string numberOfStars) {
            this.RatePersonelAsync(id, comment, numberOfStars, null);
        }
        
        /// <remarks/>
        public void RatePersonelAsync(string id, string comment, string numberOfStars, object userState) {
            if ((this.RatePersonelOperationCompleted == null)) {
                this.RatePersonelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRatePersonelOperationCompleted);
            }
            this.InvokeAsync("RatePersonel", new object[] {
                        id,
                        comment,
                        numberOfStars}, this.RatePersonelOperationCompleted, userState);
        }
        
        private void OnRatePersonelOperationCompleted(object arg) {
            if ((this.RatePersonelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RatePersonelCompleted(this, new RatePersonelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Personel_Ratings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rating_table[] Personel_Ratings(string id) {
            object[] results = this.Invoke("Personel_Ratings", new object[] {
                        id});
            return ((Rating_table[])(results[0]));
        }
        
        /// <remarks/>
        public void Personel_RatingsAsync(string id) {
            this.Personel_RatingsAsync(id, null);
        }
        
        /// <remarks/>
        public void Personel_RatingsAsync(string id, object userState) {
            if ((this.Personel_RatingsOperationCompleted == null)) {
                this.Personel_RatingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPersonel_RatingsOperationCompleted);
            }
            this.InvokeAsync("Personel_Ratings", new object[] {
                        id}, this.Personel_RatingsOperationCompleted, userState);
        }
        
        private void OnPersonel_RatingsOperationCompleted(object arg) {
            if ((this.Personel_RatingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Personel_RatingsCompleted(this, new Personel_RatingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Personel_table : Personel_table_support {
        
        private string idField;
        
        private string fnameField;
        
        private string lnameField;
        
        private string longitudeField;
        
        private string lattitudeField;
        
        private string garage_nameField;
        
        private string garage_addressField;
        
        private string specialityField;
        
        private string contactField;
        
        private string typeField;
        
        private string imageField;
        
        private string byte_imageField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Lattitude {
            get {
                return this.lattitudeField;
            }
            set {
                this.lattitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Garage_name {
            get {
                return this.garage_nameField;
            }
            set {
                this.garage_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Garage_address {
            get {
                return this.garage_addressField;
            }
            set {
                this.garage_addressField = value;
            }
        }
        
        /// <remarks/>
        public string Speciality {
            get {
                return this.specialityField;
            }
            set {
                this.specialityField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public string Byte_image {
            get {
                return this.byte_imageField;
            }
            set {
                this.byte_imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Personel_table))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Personel_table_support {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rating_table))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rating_table_support {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rating_table : Rating_table_support {
        
        private string idField;
        
        private string personelidField;
        
        private string starsField;
        
        private string commentField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Personelid {
            get {
                return this.personelidField;
            }
            set {
                this.personelidField = value;
            }
        }
        
        /// <remarks/>
        public string Stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetClass {
        
        private string keyField;
        
        private string[] wordListField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string[] WordList {
            get {
                return this.wordListField;
            }
            set {
                this.wordListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Personel_rating_view))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Personel_rating_view_support {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Personel_rating_view : Personel_rating_view_support {
        
        private string idField;
        
        private string personel_nameField;
        
        private string garage_detailsField;
        
        private string longitudeField;
        
        private string lattitudeField;
        
        private string imageField;
        
        private string byte_imageField;
        
        private string contactField;
        
        private string typeField;
        
        private string specialityField;
        
        private string commentField;
        
        private string totalStars1Field;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Personel_name {
            get {
                return this.personel_nameField;
            }
            set {
                this.personel_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Garage_details {
            get {
                return this.garage_detailsField;
            }
            set {
                this.garage_detailsField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Lattitude {
            get {
                return this.lattitudeField;
            }
            set {
                this.lattitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public string Byte_image {
            get {
                return this.byte_imageField;
            }
            set {
                this.byte_imageField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Speciality {
            get {
                return this.specialityField;
            }
            set {
                this.specialityField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string TotalStars1 {
            get {
                return this.totalStars1Field;
            }
            set {
                this.totalStars1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Personel_table[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Personel_table[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllFromTypeCompletedEventHandler(object sender, GetAllFromTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFromTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllFromTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Personel_table[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Personel_table[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SearchForSpecialityCompletedEventHandler(object sender, SearchForSpecialityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchForSpecialityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchForSpecialityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Personel_rating_view[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Personel_rating_view[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllFromTypeWithDistanceCompletedEventHandler(object sender, GetAllFromTypeWithDistanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFromTypeWithDistanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllFromTypeWithDistanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Personel_table[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Personel_table[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetPersonelByIDCompletedEventHandler(object sender, GetPersonelByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonelByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonelByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Personel_table Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Personel_table)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdatePersonelCompletedEventHandler(object sender, UpdatePersonelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePersonelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePersonelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDataSetCompletedEventHandler(object sender, GetDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RatePersonelCompletedEventHandler(object sender, RatePersonelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RatePersonelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RatePersonelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Personel_RatingsCompletedEventHandler(object sender, Personel_RatingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Personel_RatingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Personel_RatingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rating_table[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rating_table[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591