#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OldXamarinAdroid.Resource", IsApplication=true)]

namespace OldXamarinAdroid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int breakdown = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int edit_doc = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int mech = 2130903042;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int action_settings = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int button = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int button2 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int editText2 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int fab = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int garage = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int garagename = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int imageBreak = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int imageMechan = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int imageView = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int imgid = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int linkReview = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int listView = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int listViewSearch = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int name = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int progressBar = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int progressBarSearch = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int progress_bar = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int ratevslue = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int ratingBar = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int ratingBar2 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int reviewcomment = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int seekbar = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int setRating = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int specialityText = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int textView = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int textView2 = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int textView3 = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int textView5 = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int textView6 = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int toolbar = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int trash = 2130968607;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050007
			public const int activity_main = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int content_main = 2131034120;
			
			// aapt resource value: 0x7F050000
			public const int DisplayPerson = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int PersonelLayout = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ProgrssBarLayout = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ReviewRowLayout = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int SearchLayout = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int SearchRow = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int SelectionLayout = 2131034118;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int menu_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int breakdown = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int edit = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int edit_black = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int edit_doc = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int garbage = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int ic_launcher = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int ic_launcher_foreground = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int ic_launcher_round = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int mech = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int telephone = 2131165193;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int copyright = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int AppTheme_AppBarOverlay = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int AppTheme_NoActionBar = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int AppTheme_PopupOverlay = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int RatingBar = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
